services:
  service-registry:
    image: service-registry
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network
  
  api-gateway:
    image: api-gateway
    build: ./api-gateway
    ports:
      - "7078:7078"
    networks:
      - app-network
    depends_on:
      - service-registry

  auth-service:
    image: auth-service
    build: ./auth-service
    ports:
      - "7079:7079"
    networks:
      - app-network
    depends_on:
      - service-registry
      - api-gateway

  author-service:
    image: author-service
    build: ./author-service
    ports:
      - "7070:7070"
    networks:
      - app-network
    depends_on:
      - service-registry
      - api-gateway
      - auth-service
  
  book-service:
    image: book-service
    build: ./book-service
    ports:
      - "7071:7071"
    networks:
      - app-network
    depends_on:
      - service-registry
      - api-gateway
      - auth-service

networks:
  app-network: